<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Parth" ignored="0" name="Default test" tests="6" failures="1" timestamp="30 Jul 2017 09:57:11 GMT" time="46.247" errors="0">
  <testcase name="login" time="4.994" classname="com.test.automation.MastekBlanketPOM.login.TC001_Login"/>
  <testcase name="login" time="0.001" classname="com.test.automation.MastekBlanketPOM.login.TC001_Login">
    <skipped/>
  </testcase> <!-- login -->
  <testcase name="login" time="4.686" classname="com.test.automation.MastekBlanketPOM.login.TC001_Login"/>
  <testcase name="login" time="3.83" classname="com.test.automation.MastekBlanketPOM.login.TC001_Login"/>
  <testcase name="login" time="3.632" classname="com.test.automation.MastekBlanketPOM.login.TC001_Login"/>
  <testcase name="login" time="17.438" classname="com.test.automation.MastekBlanketPOM.login.TC001_Login">
    <failure type="java.lang.AssertionError" message="expected [Welcome Somesh] but found [Welcome Admin]">
      <![CDATA[java.lang.AssertionError: expected [Welcome Somesh] but found [Welcome Admin]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.test.automation.MastekBlanketPOM.login.TC001_Login.login(TC001_Login.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Default test -->
